React Calculator - Milestone 4
Berabjesus/math-magicians-calculator pull request #3
Opened 2021-02-01 21:13 UTC by Berabjesus

## React Calculator project milestone 4. The following features are implemented.
- Created logic directory and files
- Added logic to calculate and operate functions.
- Imported calculator from App.js

2021-02-01 22:39 UTC, Spayco requested changes
# Changes Requested 

Hello! 👋 
Awesome job so far!! 👍 you still need to make some changes though! 

## Required Changes ♻️ 

- [x] You have some checks missing: 
  - User pressed an operation button and there is an existing operation
  - if the button is a number 
    - If there is no operation, update next and clear total
    - If there is an operation, update next
  - if there's nothing in the `total` and `next` has a number, move the `next` value to `total`

### please make the appropriate changes and ask for another code review ✔️ 

Happy Coding!

Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2021-02-01 22:39 UTC, Spayco commented on src/logic/calculate.js
> +      operation = '';
- [ ] when `AC` is clicked, you should turn them all into `null`.

2021-02-01 22:39 UTC, Spayco commented on src/logic/calculate.js
> +      break;
- [ ] what if the number already had a dot? 🤔 then it would become something like this 25.2.3, which is not possible in a calculator.

2021-02-01 22:39 UTC, Spayco commented on src/logic/calculate.js
> +      return total;
- [ ] if the button name is `=`, and there is an operation, you should run it. (for example, if the operation was `*`, you should do `total * next` using the operate funciton.)

2021-02-01 22:39 UTC, Spayco commented on src/logic/calculate.js
> +      break;
- [ ] always return null if you try to empty a field.

2021-02-02 10:42 UTC, PhillipUg approved these changes
# Status: Project Approved! 🥇 
Congratulations on implementing all requirements and getting this milestone approved. :+1:

You can merge this branch into the development branch when you're ready and go on to your next milestone.
:bulb:  Do not forget to submit your project completion form after merging this branch.

All the best team,

For any assistance, you can contact me on slack as **Phillip Musiime** or
 <a href="mailto:phillipmusiime@gmail.com"> <img alt="gmail" src="https://img.shields.io/badge/gmail-%20- green?logo=gmail&style=social" target="_blank"></a> &nbsp; &nbsp; [![Twitter Follow](https://img.shields.io/twitter/follow/Phillip_Ug?style=social)](https://twitter.com/intent/follow?screen_name=Phillip_Ug) &nbsp; &nbsp; [![GitHub followers](https://img.shields.io/github/followers/phillipug?label=Follow&style=social)](https://github.com/PhillipUg)

2021-02-02 10:57 UTC, merged